version: "3.9"

services:
  course-service:
    build: ./course-service
    container_name: course-service
    ports:
      - 5001:5001
    networks:
      - microservice-assignment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - 5002:5002
    networks:
      - microservice-assignment-network
    env_file:
      - order-service/.env
    depends_on:
      # - course-service
      course-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  microservice-assignment-network:
    driver: bridge
